name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn install --frozen-lockfile
      - name: Style checks
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test

